# Global costmap parameters
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: "map"
      robot_base_frame: "base_link"
      update_frequency: 5.0
      publish_frequency: 2.0
      resolution: 0.05
      rolling_window: false
      width: 10.0
      height: 10.0
      robot_radius: 0.2
      obstacle_layer:
        enabled: true
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
      inflation_layer:
        inflation_radius: 0.5
        cost_scaling_factor: 10.0

# Local costmap parameters (used for local planning)
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: "odom"
      robot_base_frame: "base_link"
      update_frequency: 10.0
      publish_frequency: 5.0
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.05
      robot_radius: 0.2
      obstacle_layer:
        enabled: true
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
      inflation_layer:
        inflation_radius: 0.5
        cost_scaling_factor: 10.0

# Planner parameters (global path planner)
planner_server:
  planner_server:
    ros__parameters:
      expected_planner_frequency: 5.0
      planner_plugins: ["GridBased"]
      GridBased:
        plugin: "nav2_navfn_planner/NavfnPlanner"
        tolerance: 0.5

# Controller parameters (local controller for path following)
controller_server:
  controller_server:
    ros__parameters:
      controller_frequency: 20.0
      required_controller_plugins: ["FollowPath"]
      FollowPath:
        plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
        lookahead_distance: 0.6
        max_angular_accel: 3.2
        max_angular_velocity: 1.0
        max_linear_velocity: 0.22

# Recovery behaviors parameters
recoveries_server:
  recoveries_server:
    ros__parameters:
      costmap_clear:
        plugin: "nav2_recoveries/BackUp"
      spin_behavior:
        plugin: "nav2_recoveries/Spin"
      wait_behavior:
        plugin: "nav2_recoveries/Wait"

# Behavior tree parameters (for task coordination)
bt_navigator:
  bt_navigator:
    ros__parameters:
      behavior_tree_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml"
      plugin_lib_names: ["nav2_behavior_tree_nodes"]

# AMCL parameters (for localization)
amcl:
  amcl:
    ros__parameters:
      use_sim_time: false
      min_particles: 500
      max_particles: 2000
      alpha1: 0.2
      alpha2: 0.2
      alpha3: 0.2
      alpha4: 0.2
      alpha5: 0.1
      do_beamskip: false
      laser_likelihood_max_dist: 2.0

# Lifecycle manager (responsible for managing Nav2 nodes)
lifecycle_manager:
  lifecycle_manager:
    ros__parameters:
      use_sim_time: false
      autostart: true
      node_names: ["controller_server", "planner_server", "recoveries_server", "bt_navigator", "amcl", "map_server", "local_costmap", "global_costmap"]

