slam_toolbox:
  ros__parameters:
    use_sim_time: false                   # Use simulation time
    base_frame: base_link                # Base frame of the robot
    odom_frame: odom                     # Frame for odometry
    map_frame: map                       # Frame for the map

    # Sensor configuration
    sensor_timeout: 1.0                  # Timeout for sensor data
    publish_period: 0.1                  # Publish rate for SLAM updates
    ignore_imu: false                    # Set to true if you want to ignore IMU data
    imu_topic: /bno055/imu               # Topic for the IMU data
    laser_scan_topic: /scan              # Topic for the LiDAR data

    # SLAM algorithm parameters
    # (These can be adjusted according to your specific requirements)
    loop_closure: true                   # Enable loop closure
    publish_tracked_pose: true           # Publish tracked pose

    # Optimization parameters (adjust as necessary)
    optimization:
      max_iterations: 100                 # Maximum iterations for optimization
      optimization_time: 5.0              # Time for optimization

    # Map settings
    map:
      resolution: 0.05                    # Resolution of the map (in meters)
      initial_size: 50                    # Initial size of the map in cells
